add_item:
    resource:
        path: ../src/AddItem/
        namespace: App\AddItem
    type: attribute

cart_items:
    resource:
        path: ../src/CartItems/
        namespace: App\CartItems
    type: attribute

remove_item:
    resource:
        path: ../src/RemoveItem/
        namespace: App\RemoveItem
    type: attribute

clear_cart:
    resource:
        path: ../src/ClearCart/
        namespace: App\ClearCart
    type: attribute

change_inventory:
    resource:
        path: ../src/ChangeInventory/
        namespace: App\ChangeInventory
    type: attribute